name: Add PR Template Comment

on:
  pull_request:
    types: [opened]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment with task info and description
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          
          COMMENT_BODY="### :information_source: Task registered in Trello:
[titulo do card](https://trello.com/c/<link do card>)

### :rocket: Description:
Breve descrição do que está sendo feito na PR (adicione detalhes aqui).

---

PR Title: $PR_TITLE
PR URL: $PR_URL
PR Author: $PR_AUTHOR"

          echo "$COMMENT_BODY" > comment.txt

          # Send the comment to GitHub PR
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"body\":\"$(cat comment.txt)\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
